### ISSUE TITLE
[BUG] An ActorDiedError occurs when using transformers as the backend inference model

### ISSUE THREAD

**Issue by Ltryxcy** [ServerlessLLM/ServerlessLLM#92]
### Prerequisites

- [X] I have read the [ServerlessLLM documentation](https://serverlessllm.github.io/).
- [X] I have searched the [Issue Tracker](https://github.com/ServerlessLLM/ServerlessLLM/issues) to ensure this hasn't been reported before.

### System Information

OS: Ubuntu 22.04
Python: 3.10
GPU: A10G
Pytorch: 2.3.0

### Problem Description

Hi, I'm encountering an issue when trying to run a request for the facebook/opt-125m model using Ray and FastAPI. The actor dies unexpectedly during execution, and I'm seeing the following error message:
```
ray.exceptions.RayTaskError(ActorDiedError): ray::RoundRobinRouter.generate() 
The actor died unexpectedly before finishing this task.
        class_name: TransformersBackend
        actor_id: d7bd26fc849872815a6a102c09000000
        pid: 43620
        name: facebook/opt-125m_b0eb801f-bc1a-4f0f-ae52-016e718e8858
        namespace: b7b0b709-dc00-4f54-b7bb-9bce12a9b960
        ip: 172.31.14.189
The actor is dead because all references to the actor were removed.
```
The log indicates that the worker node is allocated correctly and the model is added to the loading queue. However, when the task starts, the actor dies unexpectedly. I'm also seeing an "Internal Server Error" (500) in the response.
Could this be due to resource limitations (GPU or memory), or is it possible there's a misconfiguration in the actor or model loading? Any advice or guidance would be greatly appreciated!

### Steps to Reproduce

Code snippets:
```python

```

Steps to reproduce:
1. sllm-cli deploy --model facebook/opt-125m --backend transformers
2. curl http://localhost:8343/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
        "model": "facebook/opt-125m",
        "messages": [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "What is your name?"}
        ]
    }'
3.

### Additional Context

```
INFO 09-19 05:05:33 app_lib.py:107] Received request for model facebook/opt-125m
INFO 09-19 05:05:33 app_lib.py:114] Got request router for facebook/opt-125m
(FcfsScheduler pid=43223) INFO 09-19 05:05:33 fcfs_scheduler.py:70] Model facebook/opt-125m requested
(FcfsScheduler pid=43223) INFO 09-19 05:05:33 fcfs_scheduler.py:80] Model facebook/opt-125m added to the loading queue
(FcfsScheduler pid=43223) INFO 09-19 05:05:33 fcfs_scheduler.py:70] Model facebook/opt-125m requested
(FcfsScheduler pid=43223) INFO 09-19 05:05:33 fcfs_scheduler.py:80] Model facebook/opt-125m added to the loading queue
(FcfsScheduler pid=43223) INFO 09-19 05:05:34 fcfs_scheduler.py:120] Worker nodes: {'0': {'ray_node_id': 'bd0ea83f69800e9cfc8467cd95f1476fc59930647b2c4322407b4b8a', 'address': '172.31.14.189', 'free_gpu': 1.0, 'total_gpu': 1.0}}
(FcfsScheduler pid=43223) INFO 09-19 05:05:34 fcfs_scheduler.py:136] Allocated node 0 for model facebook/opt-125m
(FcfsScheduler pid=43223) INFO 09-19 05:05:34 fcfs_scheduler.py:170] Worker nodes updated: {'0': {'ray_node_id': 'bd0ea83f69800e9cfc8467cd95f1476fc59930647b2c4322407b4b8a', 'address': '172.31.14.189', 'free_gpu': 0.0, 'total_gpu': 1.0}}
(FcfsScheduler pid=43223) INFO 09-19 05:05:34 fcfs_scheduler.py:120] Worker nodes: {'0': {'ray_node_id': 'bd0ea83f69800e9cfc8467cd95f1476fc59930647b2c4322407b4b8a', 'address': '172.31.14.189', 'free_gpu': 1.0, 'total_gpu': 1.0}}
(FcfsScheduler pid=43223) INFO 09-19 05:05:34 fcfs_scheduler.py:136] Allocated node 0 for model facebook/opt-125m
(FcfsScheduler pid=43223) INFO 09-19 05:05:34 fcfs_scheduler.py:170] Worker nodes updated: {'0': {'ray_node_id': 'bd0ea83f69800e9cfc8467cd95f1476fc59930647b2c4322407b4b8a', 'address': '172.31.14.189', 'free_gpu': 0.0, 'total_gpu': 1.0}}
INFO:     127.0.0.1:40730 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/starlette/routing.py", line 70, in app
    response = await func(request)
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/ubuntu/projs/ServerlessLLM/serverless_llm/serve/app_lib.py", line 117, in generate_handler
    return await result
ray.exceptions.RayTaskError(ActorDiedError): ray::RoundRobinRouter.generate() (pid=43422, ip=172.31.14.189, actor_id=22b43fdfe42a7c9ad565b65509000000, repr=<serverless_llm.serve.routers.roundrobin_router.RoundRobinRouter object at 0x70d90487ace0>)
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ubuntu/anaconda3/envs/sllm/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ubuntu/projs/ServerlessLLM/serverless_llm/serve/routers/roundrobin_router.py", line 137, in generate
    result = await instance.backend_instance.generate.remote(
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
        class_name: TransformersBackend
        actor_id: d7bd26fc849872815a6a102c09000000
        pid: 43620
        name: facebook/opt-125m_b0eb801f-bc1a-4f0f-e52-016e718e8858
        namespace: b7b0b709-dc00-4f54-b7bb-9bce12a9b960
        ip: 172.31.14.189
The actor is dead because all references to the actor were removed.
```

**Comment by SiyangShao** [comment]
I cannot reproduce this bug on my server. @future-xy Could you check more about this bug?
Here's the expected output from the server side:
```
(FcfsScheduler pid=224263) INFO 09-19 09:12:04 fcfs_scheduler.py:120] Worker nodes: {'0': {'ray_node_id':
'e021940b94a03891e22952ab9a62f363f2b82e2ed2c8ccea82d4984e', 'address': '192.168.111.145', 'free_gpu': 1.0,
 'total_gpu': 1.0}}
(FcfsScheduler pid=224263) INFO 09-19 09:12:04 fcfs_scheduler.py:136] Allocated node 0 for model facebook/
opt-125m
(FcfsScheduler pid=224263) INFO 09-19 09:12:04 fcfs_scheduler.py:170] Worker nodes updated: {'0': {'ray_no
de_id': 'e021940b94a03891e22952ab9a62f363f2b82e2ed2c8ccea82d4984e', 'address': '192.168.111.145', 'free_gp
u': 0.0, 'total_gpu': 1.0}}
(TransformersBackend pid=224482) /home/shaosy/miniconda3/envs/sllm-worker/lib/python3.10/site-packages/tra
nsformers/generation/configuration_utils.py:540: UserWarning: `do_sample` is set to `False`. However, `tem
perature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_s
ample=True` or unset `temperature`.
(TransformersBackend pid=224482)   warnings.warn(
(TransformersBackend pid=224482) /home/shaosy/miniconda3/envs/sllm-worker/lib/python3.10/site-packages/tra
nsformers/generation/configuration_utils.py:540: UserWarning: `do_sample` is set to `False`. However, `tem
perature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_s
ample=True` or unset `temperature`.

```

**Comment by future-xy** [comment]
Thanks for bringing this up!

Handling cluster-level bugs can be challenging. Could you please provide more details to help us diagnose the issue more easily? For example, are you running the Ray cluster (head and workers) on a single bare-metal machine, within a Docker cluster on one server, or across a distributed cluster?

**Comment by Ltryxcy** [comment]
> Thanks for bringing this up!
> 
> Handling cluster-level bugs can be challenging. Could you please provide more details to help us diagnose the issue more easily? For example, are you running the Ray cluster (head and workers) on a single bare-metal machine, within a Docker cluster on one server, or across a distributed cluster?

I just run the Ray cluster(head and workers) on a single machine. I encountered a bug before. When using Ray version `2.9.0`, as per your requirements, there was a segmentation fault. After updating Ray to version `2.36.0`, I was able to successfully deploy the model, but the issue mentioned above occurs during generation. Could it be due to incorrect package versions?
When I follow the Quikstart Guide, after `sllm-serve start`, the following error message occurs
```
(raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff2fd9fbb937c0aaf08388726901000000 Worker ID: b8ef3a8646f627bde6c09dfdd0bb334701cfb0619a40960fcc39327f Node ID: eea0e8ad9fdd7a55a878b7b02ecf85d4ce979029daf24446f6195474 Worker IP address: 172.31.14.189 Worker port: 10009 Worker PID: 40804 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
```
![image](https://github.com/user-attachments/assets/0e284cad-dc67-48d0-a71e-a12c61286657)
Because of this error, I upgraded the Ray version to `2.36.0`. Do you have any idea？

**Comment by anyin233** [comment]
> > Thanks for bringing this up!
> > Handling cluster-level bugs can be challenging. Could you please provide more details to help us diagnose the issue more easily? For example, are you running the Ray cluster (head and workers) on a single bare-metal machine, within a Docker cluster on one server, or across a distributed cluster?
> 
> I just run the Ray cluster(head and workers) on a single machine. I encountered a bug before. When using Ray version `2.9.0`, as per your requirements, there was a segmentation fault. After updating Ray to version `2.36.0`, I was able to successfully deploy the model, but the issue mentioned above occurs during generation. Could it be due to incorrect package versions? When I follow the Quikstart Guide, after `sllm-serve start`, the following error message occurs
> 
> ```
> (raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. 
> RayTask ID: ffffffffffffffff2fd9fbb937c0aaf08388726901000000 
> Worker ID: b8ef3a8646f627bde6c09dfdd0bb334701cfb0619a40960fcc39327f 
> Node ID: eea0e8ad9fdd7a55a878b7b02ecf85d4ce979029daf24446f6195474 
> Worker IP address: 172.31.14.189 Worker port: 10009 Worker PID: 40804 
> Worker exit type: SYSTEM_ERROR Worker exit 
> detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. 
> (1) The process is killed by SIGKILL by OOM killer due to high memory usage. 
> (2) ray stop --force is called. 
> (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/96286062/368956829-0e284cad-dc67-48d0-a71e-a12c61286657.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTE2MzAsIm5iZiI6MTcyNjc1MTMzMCwicGF0aCI6Ii85NjI4NjA2Mi8zNjg5NTY4MjktMGUyODRjYWQtZGM2Ny00OGQwLWE3MWUtYTEyYzYxMjg2NjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDEzMDg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZTk4MjY3ZGZhMTU4NmUxZTJiYjU1YzdmOGNjN2IwNTMzYWQxNjYwZmJjZDNhYWEwY2Y0NmNmOTQ1NzkzNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IT_ZGKMEA1e0rOn8U7U1_mXCNRT85TZhaq9_hMWuzfs) I find this error in `ServerlessLLM/serverless_llm/serve/schedulers/fcfs_scheduler.py function _control_loop`. Because of this error, I upgraded the Ray version to `2.36.0`. Do you have any idea？

I encountered the same problem before, but it was resolved after I cleaned my Conda environments and reinstalled ServerlessLLM with Ray version 2.9.0. You might want to try cleaning your environment and following the quick start guide.

**Comment by Ltryxcy** [comment]
> > > Thanks for bringing this up!
> > > Handling cluster-level bugs can be challenging. Could you please provide more details to help us diagnose the issue more easily? For example, are you running the Ray cluster (head and workers) on a single bare-metal machine, within a Docker cluster on one server, or across a distributed cluster?
> > 
> > 
> > I just run the Ray cluster(head and workers) on a single machine. I encountered a bug before. When using Ray version `2.9.0`, as per your requirements, there was a segmentation fault. After updating Ray to version `2.36.0`, I was able to successfully deploy the model, but the issue mentioned above occurs during generation. Could it be due to incorrect package versions? When I follow the Quikstart Guide, after `sllm-serve start`, the following error message occurs
> > ```
> > (raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. 
> > RayTask ID: ffffffffffffffff2fd9fbb937c0aaf08388726901000000 
> > Worker ID: b8ef3a8646f627bde6c09dfdd0bb334701cfb0619a40960fcc39327f 
> > Node ID: eea0e8ad9fdd7a55a878b7b02ecf85d4ce979029daf24446f6195474 
> > Worker IP address: 172.31.14.189 Worker port: 10009 Worker PID: 40804 
> > Worker exit type: SYSTEM_ERROR Worker exit 
> > detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. 
> > (1) The process is killed by SIGKILL by OOM killer due to high memory usage. 
> > (2) ray stop --force is called. 
> > (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/96286062/368956829-0e284cad-dc67-48d0-a71e-a12c61286657.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTE2MzAsIm5iZiI6MTcyNjc1MTMzMCwicGF0aCI6Ii85NjI4NjA2Mi8zNjg5NTY4MjktMGUyODRjYWQtZGM2Ny00OGQwLWE3MWUtYTEyYzYxMjg2NjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDEzMDg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZTk4MjY3ZGZhMTU4NmUxZTJiYjU1YzdmOGNjN2IwNTMzYWQxNjYwZmJjZDNhYWEwY2Y0NmNmOTQ1NzkzNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IT_ZGKMEA1e0rOn8U7U1_mXCNRT85TZhaq9_hMWuzfs) I find this error in `ServerlessLLM/serverless_llm/serve/schedulers/fcfs_scheduler.py function _control_loop`. Because of this error, I upgraded the Ray version to `2.36.0`. Do you have any idea？
> 
> I encountered the same problem before, but it was resolved after I cleaned my Conda environments and reinstalled ServerlessLLM with Ray version 2.9.0. You might want to try cleaning your environment and following the quick start guide.

Thanks! I cleaned my conda environments and reinstalled sllm and sllm-worker, but unfortunately, the segmentation fault above occurred again.

**Comment by future-xy** [comment]
As @anyin233 mentioned, the bug disappeared after reinstalling the conda environments, so we are currently unable to reproduce the issue.

It seems like the bug might be related to Ray's `logging.cc`. Could you try cleaning up Ray's cache directories, typically located at `~/.ray` and `/tmp/ray*`, and then run your code again?

Additionally, it appears that you might be running a stale or custom version of ServerlessLLM.

> ```
>   File "/home/ubuntu/projs/ServerlessLLM/serverless_llm/serve/routers/roundrobin_router.py", line 137, in generate
>     result = await instance.backend_instance.generate.remote(
> ```

This line of code should be at line 131 in the current main branch:
https://github.com/ServerlessLLM/ServerlessLLM/blob/9b6a4db5e9cd4a6ae0fa7c8cbca9e968322b309c/serverless_llm/serve/routers/roundrobin_router.py#L131

If that's the case, could you please try installing and testing the latest version from the main branch?

**Comment by Ltryxcy** [comment]
I followed your suggestions and reinstalled the latest version, but I'm still encountering the same issue during the `sllm-serve start` step. I suspect it might be a problem with the version of `boost.fiber`. Could you please provide the versions of `boost.fiber` and `boost` that you are using?

**Comment by future-xy** [comment]
The Boost version on our server is 1.74. It appears that this bug might be related to a previous issue in Ray (https://github.com/ray-project/ray/issues/46151). This likely explains why updating to the latest version of Ray resolved the problem, as you mentioned.

**Comment by future-xy** [comment]
We can now consistently reproduce this bug. If `pyarrow==17.0.0` is mistakenly installed in the **`sllm` environment** (instead of the `sllm-worker` environment), either explicitly or implicitly, the FCFS scheduler crashes, and Ray reports a `Fatal Python error: Segmentation fault`. Here is the error message we reproduced:

```
$ sllm-serve start
2024-09-23 20:43:46,316 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 129.215.164.41:6379...
2024-09-23 20:43:46,346 INFO worker.py:1724 -- Connected to Ray cluster.
(StoreManager pid=1114474) INFO 09-23 20:44:04 store_manager.py:194] Initializing store manager
(StoreManager pid=1114474) INFO 09-23 20:44:04 store_manager.py:194] Initializing store manager
(StoreManager pid=1114474) WARNING 09-23 20:44:04 store_manager.py:206] Hardware info not provided. Storage-aware scheduling might not work properly
INFO:     Started server process [1113645]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8343 (Press CTRL+C to quit)
(StoreManager pid=1114474) WARNING 09-23 20:44:04 store_manager.py:206] Hardware info not provided. Storage-aware scheduling might not work properly
(FcfsScheduler pid=1114660) INFO 09-23 20:44:06 fcfs_scheduler.py:53] Starting FCFS scheduler
(FcfsScheduler pid=1114660) INFO 09-23 20:44:06 fcfs_scheduler.py:94] Starting control loop
(FcfsScheduler pid=1114660) INFO 09-23 20:44:06 fcfs_scheduler.py:53] Starting FCFS scheduler
(FcfsScheduler pid=1114660) INFO 09-23 20:44:06 fcfs_scheduler.py:94] Starting control loop
(FcfsScheduler pid=1114660) *** SIGSEGV received at time=1727120649 on cpu 48 ***
(FcfsScheduler pid=1114660) PC: @     0x75a2a62debab  (unknown)  boost::fibers::detail::spinlock_ttas::lock()
(FcfsScheduler pid=1114660)     @     0x75a2a8042520       8112  (unknown)
(FcfsScheduler pid=1114660)     @     0x75a2a643a980         64  boost::fibers::mutex::lock()
(FcfsScheduler pid=1114660)     @     0x75a2a63d16dd         96  std::_Function_handler<>::_M_invoke()
(FcfsScheduler pid=1114660)     @     0x75a2a63cb895         96  boost::fibers::worker_context<>::run_()
(FcfsScheduler pid=1114660)     @     0x75a2a63cb610         80  boost::context::detail::fiber_entry<>()
(FcfsScheduler pid=1114660)     @     0x75a2a643badf  (unknown)  make_fcontext
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361: *** SIGSEGV received at time=1727120649 on cpu 48 ***
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361: PC: @     0x75a2a62debab  (unknown)  boost::fibers::detail::spinlock_ttas::lock()
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a8042520       8112  (unknown)
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a643a980         64  boost::fibers::mutex::lock()
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a63d16dd         96  std::_Function_handler<>::_M_invoke()
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a63cb895         96  boost::fibers::worker_context<>::run_()
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a63cb610         80  boost::context::detail::fiber_entry<>()
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a643badf  (unknown)  make_fcontext
(FcfsScheduler pid=1114660) Fatal Python error: Segmentation fault
(FcfsScheduler pid=1114660) 
(FcfsScheduler pid=1114660) 
(FcfsScheduler pid=1114660) Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, uvloop.loop, ray._raylet, numpy._core._multiarray_umath, numpy.linalg._umath_linalg, pyarrow.lib, pyarrow._json (total: 15)
(FcfsScheduler pid=1114660) *** SIGSEGV received at time=1727120649 on cpu 48 ***
(FcfsScheduler pid=1114660) PC: @     0x75a2a62debab  (unknown)  boost::fibers::detail::spinlock_ttas::lock()
(FcfsScheduler pid=1114660)     @     0x75a2a8042520       8112  (unknown)
(FcfsScheduler pid=1114660)     @     0x75a2a643a980         64  boost::fibers::mutex::lock()
(FcfsScheduler pid=1114660)     @     0x75a2a63d16dd         96  std::_Function_handler<>::_M_invoke()
(FcfsScheduler pid=1114660)     @     0x75a2a63cb895         96  boost::fibers::worker_context<>::run_()
(FcfsScheduler pid=1114660)     @     0x75a2a63cb610         80  boost::context::detail::fiber_entry<>()
(FcfsScheduler pid=1114660)     @     0x75a2a643badf  (unknown)  make_fcontext
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361: *** SIGSEGV received at time=1727120649 on cpu 48 ***
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361: PC: @     0x75a2a62debab  (unknown)  boost::fibers::detail::spinlock_ttas::lock()
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a8042520       8112  (unknown)
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a643a980         64  boost::fibers::mutex::lock()
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a63d16dd         96  std::_Function_handler<>::_M_invoke()
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a63cb895         96  boost::fibers::worker_context<>::run_()
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a63cb610         80  boost::context::detail::fiber_entry<>()
(FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a643badf  (unknown)  make_fcontext
(FcfsScheduler pid=1114660) Fatal Python error: Segmentation fault
(FcfsScheduler pid=1114660) 
(FcfsScheduler pid=1114660) 
(FcfsScheduler pid=1114660) Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, uvloop.loop, ray._raylet, numpy._core._multiarray_umath, numpy.linalg._umath_linalg, pyarrow.lib, pyarrow._json (total: 15)
(raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff4b7e4786f60bb5faadbb9baf01000000 Worker ID: 963240044c68bc2ceb8fd70e30e7ea2d771bdd76863191da491dd423 Node ID: 7e781bf5dd861842de5835135b47f88a7f3bb27e2da3cc60cbb40b1f Worker IP address: 129.215.164.41 Worker port: 10009 Worker PID: 1114660 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
```

`pyarrow` is installed as a dependency of `vllm`, so it’s possible that during development, `vllm` (or `requirements-worker.txt`) was installed in the `sllm` environment.

I'm not entirely sure why this would happen, but if this doesn’t align with your case, could you please provide a list of Python libraries installed in your `sllm` environment?

**Comment by Ltryxcy** [comment]
> We can now consistently reproduce this bug. If `pyarrow==17.0.0` is mistakenly installed in the **`sllm` environment** (instead of the `sllm-worker` environment), either explicitly or implicitly, the FCFS scheduler crashes, and Ray reports a `Fatal Python error: Segmentation fault`. Here is the error message we reproduced:
> 
> ```
> $ sllm-serve start
> 2024-09-23 20:43:46,316 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 129.215.164.41:6379...
> 2024-09-23 20:43:46,346 INFO worker.py:1724 -- Connected to Ray cluster.
> (StoreManager pid=1114474) INFO 09-23 20:44:04 store_manager.py:194] Initializing store manager
> (StoreManager pid=1114474) INFO 09-23 20:44:04 store_manager.py:194] Initializing store manager
> (StoreManager pid=1114474) WARNING 09-23 20:44:04 store_manager.py:206] Hardware info not provided. Storage-aware scheduling might not work properly
> INFO:     Started server process [1113645]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://0.0.0.0:8343 (Press CTRL+C to quit)
> (StoreManager pid=1114474) WARNING 09-23 20:44:04 store_manager.py:206] Hardware info not provided. Storage-aware scheduling might not work properly
> (FcfsScheduler pid=1114660) INFO 09-23 20:44:06 fcfs_scheduler.py:53] Starting FCFS scheduler
> (FcfsScheduler pid=1114660) INFO 09-23 20:44:06 fcfs_scheduler.py:94] Starting control loop
> (FcfsScheduler pid=1114660) INFO 09-23 20:44:06 fcfs_scheduler.py:53] Starting FCFS scheduler
> (FcfsScheduler pid=1114660) INFO 09-23 20:44:06 fcfs_scheduler.py:94] Starting control loop
> (FcfsScheduler pid=1114660) *** SIGSEGV received at time=1727120649 on cpu 48 ***
> (FcfsScheduler pid=1114660) PC: @     0x75a2a62debab  (unknown)  boost::fibers::detail::spinlock_ttas::lock()
> (FcfsScheduler pid=1114660)     @     0x75a2a8042520       8112  (unknown)
> (FcfsScheduler pid=1114660)     @     0x75a2a643a980         64  boost::fibers::mutex::lock()
> (FcfsScheduler pid=1114660)     @     0x75a2a63d16dd         96  std::_Function_handler<>::_M_invoke()
> (FcfsScheduler pid=1114660)     @     0x75a2a63cb895         96  boost::fibers::worker_context<>::run_()
> (FcfsScheduler pid=1114660)     @     0x75a2a63cb610         80  boost::context::detail::fiber_entry<>()
> (FcfsScheduler pid=1114660)     @     0x75a2a643badf  (unknown)  make_fcontext
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361: *** SIGSEGV received at time=1727120649 on cpu 48 ***
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361: PC: @     0x75a2a62debab  (unknown)  boost::fibers::detail::spinlock_ttas::lock()
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a8042520       8112  (unknown)
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a643a980         64  boost::fibers::mutex::lock()
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a63d16dd         96  std::_Function_handler<>::_M_invoke()
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a63cb895         96  boost::fibers::worker_context<>::run_()
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a63cb610         80  boost::context::detail::fiber_entry<>()
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a643badf  (unknown)  make_fcontext
> (FcfsScheduler pid=1114660) Fatal Python error: Segmentation fault
> (FcfsScheduler pid=1114660) 
> (FcfsScheduler pid=1114660) 
> (FcfsScheduler pid=1114660) Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, uvloop.loop, ray._raylet, numpy._core._multiarray_umath, numpy.linalg._umath_linalg, pyarrow.lib, pyarrow._json (total: 15)
> (FcfsScheduler pid=1114660) *** SIGSEGV received at time=1727120649 on cpu 48 ***
> (FcfsScheduler pid=1114660) PC: @     0x75a2a62debab  (unknown)  boost::fibers::detail::spinlock_ttas::lock()
> (FcfsScheduler pid=1114660)     @     0x75a2a8042520       8112  (unknown)
> (FcfsScheduler pid=1114660)     @     0x75a2a643a980         64  boost::fibers::mutex::lock()
> (FcfsScheduler pid=1114660)     @     0x75a2a63d16dd         96  std::_Function_handler<>::_M_invoke()
> (FcfsScheduler pid=1114660)     @     0x75a2a63cb895         96  boost::fibers::worker_context<>::run_()
> (FcfsScheduler pid=1114660)     @     0x75a2a63cb610         80  boost::context::detail::fiber_entry<>()
> (FcfsScheduler pid=1114660)     @     0x75a2a643badf  (unknown)  make_fcontext
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361: *** SIGSEGV received at time=1727120649 on cpu 48 ***
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361: PC: @     0x75a2a62debab  (unknown)  boost::fibers::detail::spinlock_ttas::lock()
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a8042520       8112  (unknown)
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a643a980         64  boost::fibers::mutex::lock()
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a63d16dd         96  std::_Function_handler<>::_M_invoke()
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a63cb895         96  boost::fibers::worker_context<>::run_()
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a63cb610         80  boost::context::detail::fiber_entry<>()
> (FcfsScheduler pid=1114660) [2024-09-23 20:44:09,379 E 1114660 1114762] logging.cc:361:     @     0x75a2a643badf  (unknown)  make_fcontext
> (FcfsScheduler pid=1114660) Fatal Python error: Segmentation fault
> (FcfsScheduler pid=1114660) 
> (FcfsScheduler pid=1114660) 
> (FcfsScheduler pid=1114660) Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, uvloop.loop, ray._raylet, numpy._core._multiarray_umath, numpy.linalg._umath_linalg, pyarrow.lib, pyarrow._json (total: 15)
> (raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff4b7e4786f60bb5faadbb9baf01000000 Worker ID: 963240044c68bc2ceb8fd70e30e7ea2d771bdd76863191da491dd423 Node ID: 7e781bf5dd861842de5835135b47f88a7f3bb27e2da3cc60cbb40b1f Worker IP address: 129.215.164.41 Worker port: 10009 Worker PID: 1114660 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
> ```
> 
> `pyarrow` is installed as a dependency of `vllm`, so it’s possible that during development, `vllm` (or `requirements-worker.txt`) was installed in the `sllm` environment.
> 
> I'm not entirely sure why this would happen, but if this doesn’t align with your case, could you please provide a list of Python libraries installed in your `sllm` environment?

Thank you very much! I have solved this problem by removing `pyarrow` in `sllm` environment. By the way,I notice that every time I use `sllm-cli deploy` for a model, it seems to always download the model again to the local directory. Could you please let me know if `sllm-cli` can deploy using an existing local model instead of downloading it again?

**Comment by future-xy** [comment]
> Thank you very much! I have solved this problem by removing `pyarrow` in `sllm` environment. By the way,I notice that every time I use `sllm-cli deploy` for a model, it seems to always download the model again to the local directory. Could you please let me know if `sllm-cli` can deploy using an existing local model instead of downloading it again?

ServerlessLLM currently supports reusing the downloaded model for the transformer backend:  
https://github.com/ServerlessLLM/ServerlessLLM/blob/6a6e781f6a491b92380c779f836213fd14de4061/serverless_llm/serve/model_downloader.py#L43-L45

We will fix this in the vLLM backend soon.
